name: Main Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  gitleaks:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2

  codeql:
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

  docker:
    needs: codeql
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: task-manager
    secrets: inherit

  trivy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

  dast:
    needs: trivy
    runs-on: ubuntu-latest
    steps:
      - name: Run App Container
        run: |
          docker run -d --network host ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}

          echo "Waiting for app..."
          for i in {1..15}; do
            if curl -s http://localhost:5000 > /dev/null; then
              echo "App is UP ✅"
              break
            fi
            echo "Retrying..."
            sleep 5
          done

      - name: Run ZAP Scan (FINAL FIX)
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: "http://localhost:5000"
          allow_issue_writing: false
          cmd_options: "-silent -nostats -config api.disablekey=true"

  deploy:
    needs: [docker, dast]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying image:${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}"